---
language: node_js
node_js:
  - "0.12"
  - "4.2"
#  - "6" - The test that includes coverage runs with 6

sudo: false

cache:
  directories:
    - node_modules

env:
  - NPM_SCRIPT=node-test

matrix:
  fast_finish: true
  include:
  - node_js: "4.2"
    env: NPM_SCRIPT=client-test
  - node_js: "6"
    env: NPM_SCRIPT=jscs
  - node_js: "6"
    env: NPM_SCRIPT=lint
  - node_js: "6"
    env: NPM_SCRIPT=node-test-with-coverage

before_install:
  - npm config set spin false
  - npm install -g bower
  - bower --version
  - npm install phantomjs-prebuilt
  - node_modules/phantomjs-prebuilt/bin/phantomjs --version

install:
  - npm install
  - bower install

script:
  - npm run-script $NPM_SCRIPT
