---
language: node_js
node_js:
  - "4"
  - "7"
  - "8"
#  - "6" - The test that includes coverage runs with 6

sudo: false

env:
  - NPM_SCRIPT=node-test

matrix:
  fast_finish: true
  include:
  - node_js: "6"
    env: NPM_SCRIPT=client-test
  - node_js: "6"
    env: NPM_SCRIPT=lint
  - node_js: "6"
    env: NPM_SCRIPT=node-test-with-coverage
  - node_js: "4"
    env: NPM_SCRIPT=smoke-test
  - node_js: "6"
    env: NPM_SCRIPT=smoke-test
  - node_js: "8"
    env: NPM_SCRIPT=smoke-test

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn --version
  - npm config set spin false
  - npm install -g bower
  - bower --version
  - npm install -g phantomjs-prebuilt
  - phantomjs --version

install:
  - npm install

script:
  - npm run-script $NPM_SCRIPT
