# https://www.appveyor.com/docs/appveyor-yml/

# Test against these versions of Node.js.
skip_branch_with_pr: true
environment:
  MOCHA_REPORTER: "mocha-appveyor-reporter"
  matrix:
    - nodejs_version: "10"

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version
  - appveyor-retry npm i -g npm@^4
  - appveyor-retry yarn
  - appveyor-retry yarn add mocha-appveyor-reporter # must be installed locally.

cache:
  - '%LOCALAPPDATA%\Yarn'

# Post-install test scripts.
test_script:
  - npm version
  - cmd: del "ember-try*.tgz" >nul 2>&1
  - cmd: npm pack
  - cmd: set ran=%RANDOM%
  - cmd: move "ember-try*.tgz" "ember-try-%ran%.tgz"
  - cmd: cd smoke-test-app
  - cmd: yarn upgrade "ember-try@../ember-try-%ran%.tgz"
  - cmd: yarn install
  - cmd: node_modules/.bin/ember try:one test1 --config-path="../test/fixtures/dummy-ember-try-config.js"

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"
